# Generated by Django 2.2.12 on 2020-05-02 01:56

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumbyArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_title', models.CharField(max_length=500, verbose_name='Título del álbum')),
                ('zipfile', models.FileField(upload_to='media/')),
                ('precio', models.IntegerField(default=10)),
                ('sell', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mención')),
                ('descrip', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen')),
                ('linkV', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('cuerpo_noticia', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=200, verbose_name='Titular')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='VideoP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', embed_video.fields.EmbedVideoField()),
                ('titulo', models.CharField(max_length=80, verbose_name='Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='SongsbyAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_title', models.CharField(max_length=500, verbose_name='Título de la canción')),
                ('file', models.FileField(upload_to='media/')),
                ('Album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.AlbumbyArtist')),
                ('Artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Artistas')),
            ],
        ),
        migrations.AddField(
            model_name='albumbyartist',
            name='Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Artistas'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web.Category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
